### ISSUE TITLE
packr: not found

### ISSUE THREAD

**Issue by 9code7** [sarahc0nn0r/ultranet#2]
Installed dependencies on Ubuntu 18 64-bit. After running build.sh I received these errors for each binary:
```
Building for 64-bit Linux...
./build.sh: 16: ./build.sh: packr: not found
Building for 32-bit Linux...
./build.sh: 19: ./build.sh: packr: not found
```
.
.
Any ideas?

**Comment by sarahc0nn0r** [comment]
It looks like you need to install [packr](https://github.com/gobuffalo/packr). Can you try one of the commands below and then recompile with ./build.sh? Let me know what works from here and I'll add it to the instructions.

$ go get -u github.com/gobuffalo/packr/packr
$ go get -u github.com/gobuffalo/packr
$ go get -u packr

Also sorry for the delay. I've been very busy preparing for launch on Tuesday. I should be faster to respond now.

**Comment by 9code7** [comment]
Thanks. I ran all 3 of the commands you suggested. The first two appear to have done something, but in both cases no message was returned after running the commands. The last command (`go get -u packr`) produced this message:

package packr: unrecognized import path "packr" (import path does not begin with host name)

Then I tried `./build.sh` again but it produced the same output as seen in my first issue comment. Also, I checked `/bin/ultranet_binaries` to see if anything was produced, but the directory was empty.

**Comment by sarahc0nn0r** [comment]
Ok, I have a few more things to try below.

First, can you make sure your $GOPATH environment variable is set? You can check by running "echo $GOPATH". If it isn't set, you will need to set it to the directory containing your src, bin, and pkg directories. Let me know if you need help with this.

Assuming your $GOPATH is set, can you confirm that the packr binary is available under $GOPATH/bin? You can can check by doing "ls $GOPATH/bin/packr". If it isn't there let me know (it should be).

If your $GOPATH is set and packr is in the bin directory then the problem is that your $GOPATH hasn't been added to your $PATH environment variable. To fix this, you can add the following to your ~/.bashrc (or your ~/.bash_profile on mac):
export GOBIN="$GOPATH/bin"
PATH="$GOBIN:$PATH"

Then source your bashrc file to pick up the change using "source ~/.bashrc" and run build.sh again afterward.

If you need any more clarification or help from the above let me know and I'll be happy to expand/assist.

And if you get through all of this and actually get it up and running give me your address so I can send you some Ultra for all the hard work :)

**Comment by 9code7** [comment]
Thanks. `echo $GOPATH` produced nothing so I tried the following but still couldn't get `./build.sh` to compile:
`nano ~/.bash_profile`
In that file I entered:
`GOPATH=/usr/bin/go:home/me/ultranet:/bin/ultranet_binaries`
Then I ran
`source ~/.bash_profile` and finally `./build.sh`
I'm guessing my GOPATH settings are not correct? Thanks for helping!

**Comment by sarahc0nn0r** [comment]
Ok, so the problem was your GOPATH wasn't set, but your solution is incorrect. Your GOPATH needs to be a single directory in which all of your go packages will live. To set it properly please do the following.

Create your go working directory:

* mkdir /home/me/go_workingdir

In your .bash_profile set:

* GOPATH=/home/me/go_workingdir
* PATH=$PATH:$GOPATH/bin

Then do:

* $ source ~/.bash_profile
* $ go get -u github.com/sarahc0nn0r/ultranet
* $ cd $GOPATH/src/github.com/sarahc0nn0r/ultranet
* $ ./build.sh

Let me know how that goes.

**Comment by sarahc0nn0r** [comment]
I am closing this issue since I have not heard back and since it seems to be an issue with the user's environment rather than with the Ultranet itself.
