### ISSUE TITLE
fix-badgerOptions

### ISSUE THREAD

**Issue by MathisWellmann** [sarahc0nn0r/ultranet#4]
Two issues when building backend/main.go which I already fixed in my local branch but cannot push and create pull-request as this options seems to be disabled. Please enable the possibility for other developers to create pull-requests as this is a cornerstone of Censorship-resistant development.
Anyway: here is my fix which enable main.go to be build without compiler error:
instead of 

opts := badger.DefaultOptions
opts.Dir = lib.GetBadgerDbPath(dataDir)

in line 525 do:

path := lib.GetBadgerDbPath(dataDir)
opts := badger.DefaultOptions(path)

as this is how to properly call the function. It will otherwise throw an error.

also change import path of
 "ultranet/backend/lib"
to 
"github.com/sarahc0nn0r/ultranet/backend/lib"
as the go compiler can otherwise not find the package.

Thanks for this great piece of software. Looking forward to more open code collaboration.

**Comment by sarahc0nn0r** [comment]
Hey, I really appreciate this. I'm trying to sort out the permissions to make it so that anyone can submit a pull request but it seems the only thing the repo settings allow is for "collaborators" to submit pull requests. This is pretty unacceptable, though, because I would much prefer people be able to submit PR's without needing to be added as collaborators first. **Do you have any experience with this by any chance?** I'm a bit new to github so it's highly likely I'm missing something here.

For now, since it seems you really care about the project, I added you as a collaborator directly. If you could submit a PR for this change that would be awesome. And if there are any other changes you want to make, I hope you won't hesitate to make them and submit them as PR's and merge them after I've had a chance to take a look. And if you have any friends who you think might be interested in contributing, please let them know so we can have more help. We're going to need all the help we can get if we want to really challenge the Amazon's of the world.

**Comment by MathisWellmann** [comment]
Hi, I Appreciate you adding me as a collaborator, I will do my best. It appears that the Github Free Accounts are limited in regards to managing pull-requests. It looks like there is an account type for  open-source projects which allows greater control (see https://opensource.guide/starting-a-project/). This document provides insights into setting everything up.
Kind Regards,
Mathis
